name: Test Extension
description: Run VS Code extension tests

runs:
  using: composite
  steps:
    - name: Install Xvfb (Linux only)
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install -y xvfb

    - name: Run extension tests (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: xvfb-run -a npm test
      working-directory: extension

    - name: Run extension tests (macOS and Windows)
      if: runner.os != 'Linux'
      shell: bash
      run: npm test
      working-directory: extension
