/**
 * Report-database version check and migration, driven through the
 * `idaes_fi.structfs.check_db_version` and `idaes_fi.structfs.db_migration`
 * CLIs of flowsheet-inspector-lib (console scripts `check-db-version` and
 * `db-migration`, one module per command, no subcommands).
 *
 * The SQLite report DB carries a schema version (`version` table, one row of
 * major/minor). When the user upgrades the Python lib, an old DB can be
 * incompatible: fi-run then refuses to run (exit code 3). This module lets
 * the extension detect that state up front (so the sidebar can show an
 * "Upgrade FI DB" button) and perform the migration on the user's behalf.
 *
 * Both commands are spawned with the interpreter the user selected in VS Code
 * (same approach as fi-steps / fi-run: no shell, no conda activate). They
 * print exactly one line of JSON as the LAST line of stdout; log noise before
 * it is tolerated by scanning from the end, mirroring runFiSteps.
 */
import * as cp from 'child_process';
import { type IResolvedPythonEnv, activatedProcessEnv } from './python_env';
import { getIdaesDbPath } from './platform_config';

/** Python module implementing `check-db-version`. */
export const CHECK_DB_VERSION_MODULE = 'idaes_fi.structfs.check_db_version';

/** Python module implementing `db-migration`. */
export const DB_MIGRATION_MODULE = 'idaes_fi.structfs.db_migration';

/**
 * Exit code fi-run uses for any report DB problem (schema too old, too new,
 * or unreadable) before writing anything. The frontend re-runs
 * `check-db-version` on it to learn which case applies.
 */
export const FI_RUN_EXIT_DB_ERROR = 3;

/**
 * Report DB state, derived by the extension from the three keys the CLI
 * prints (`is_db_version_low`, `client_db_version`,
 * `flowsheet_inspector_lib_db_version`):
 *   - needs_migration     is_db_version_low is true (older or legacy DB)
 *   - incompatible_newer  DB version is greater than the lib's
 *   - missing             no DB / no tables yet (client version 0.0, not low)
 *   - ok                  versions match
 *   - invalid             the CLI could not read the file (exit 1, ERROR on stderr)
 *   - unavailable         the check itself could not run, e.g. the installed
 *                         lib predates `check_db_version`
 */
export type ReportDbStatus =
    | 'ok'
    | 'needs_migration'
    | 'incompatible_newer'
    | 'missing'
    | 'invalid'
    | 'unavailable';

/** Report DB check as broadcast to the sidebar webview. */
export interface IReportDbCheck {
    status: ReportDbStatus;
    /** The flag to act on: true iff the file's schema is older than the lib's. */
    is_db_version_low: boolean;
    /** Default report DB path as the extension computes it (the CLI no longer reports it). */
    db_file: string;
    /** Schema version of the DB file (e.g. "1.1"; "0.0" for legacy/missing). */
    client_db_version: string | null;
    /** Schema version the installed lib writes. */
    lib_db_version: string | null;
    /** Human-readable explanation generated by the extension, safe to show verbatim. */
    message: string;
}

/**
 * Outcome of `db-migration`: the pre-migration check plus what happened.
 * `ok` mirrors the exit code (true when the DB is not outdated afterwards,
 * whether it was migrated, already current, missing, or newer than the lib).
 */
export interface IReportDbMigration extends IReportDbCheck {
    ok: boolean;
    migrated: boolean;
    backup_file: string | null;
    rows_migrated: number;
}

/**
 * Message shown in place of the step list when fi-steps cannot run because
 * the report database is outdated or newer than the lib (fi-steps exits 3
 * before importing the flowsheet, so no steps are available).
 */
export const STEPS_BLOCKED_BY_DB_MSG =
    'Flowsheet steps are unavailable until the report database issue shown above is resolved.';

/**
 * Tells whether a check result means fi-steps / fi-run will refuse to run:
 * the DB is older than the lib (update button) or newer (upgrade the lib).
 *
 * @param check The latest check result, or null when no check has run.
 * @returns True when the sidebar should treat the DB as blocking.
 */
export function reportDbBlocksRun(check: IReportDbCheck | null): boolean {
    return !!check && (check.is_db_version_low || check.status === 'incompatible_newer');
}

/**
 * Runs one of the DB CLI modules and returns its stdout, stderr and exit code.
 *
 * Why a plain runner instead of execFile: stdout and stderr must both be
 * captured in full so a failure can be reported with the lib's own message,
 * and a non-zero exit is a legitimate result for `db-migration` (refusal)
 * rather than a spawn failure.
 *
 * @param env    The resolved Python environment selected in VS Code.
 * @param module Python module to run with `-m` (check or migrate module).
 * @param args   Arguments after the module, e.g. `['--db', path]`.
 * @returns The captured output and exit code once the process closes.
 * @throws If the interpreter cannot be spawned at all.
 */
function runDbModule(
    env: IResolvedPythonEnv,
    module: string,
    args: string[],
): Promise<{ stdout: string; stderr: string; code: number | null }> {
    return new Promise((resolve, reject) => {
        const child = cp.spawn(
            env.interpreterPath,
            ['-m', module, ...args],
            { stdio: 'pipe', windowsHide: true, env: activatedProcessEnv(env) },
        );
        let stdout = '';
        let stderr = '';
        child.stdout.on('data', (d) => { stdout += d.toString(); });
        child.stderr.on('data', (d) => { stderr += d.toString(); });
        child.on('error', reject);
        child.on('close', (code) => resolve({ stdout, stderr, code }));
    });
}

/**
 * Converts an optional JSON field to a string, keeping null/undefined as null.
 * Versions arrive as JSON numbers (e.g. 1.1) and are shown, never compared,
 * on the frontend, so stringifying them is safe.
 *
 * @param value Raw parsed JSON value.
 * @returns The value as a string, or null when absent.
 */
function strOrNull(value: unknown): string | null {
    return value === null || value === undefined ? null : String(value);
}

/**
 * Formats a schema version for display. The CLI emits versions as JSON
 * numbers, so `0.0` arrives as the integer 0 and would print as "0"; whole
 * numbers get an explicit ".0" so the UI always shows major.minor.
 *
 * @param value Raw parsed JSON value (number or absent).
 * @returns The version string, or null when absent.
 */
function versionStr(value: unknown): string | null {
    if (typeof value === 'number' && Number.isInteger(value)) {
        return `${value}.0`;
    }
    return strOrNull(value);
}

/**
 * Extracts the single JSON object the CLI prints as the last stdout line.
 *
 * Scans from the end for the first line starting with `{` so any logging the
 * lib (or an import-time warning) writes before it does not break parsing.
 *
 * @param stdout Full captured stdout of the command.
 * @returns The parsed object, or null when no JSON object line is present.
 */
function parseLastJsonLine(stdout: string): Record<string, unknown> | null {
    const lines = stdout.trim().split('\n').reverse();
    const jsonLine = lines.find((l) => l.trim().startsWith('{'));
    if (!jsonLine) {
        return null;
    }
    try {
        return JSON.parse(jsonLine.trim()) as Record<string, unknown>;
    } catch {
        return null;
    }
}

/**
 * Parses the check-db-version JSON that fi-steps / fi-run print as the last
 * stdout line when they refuse to run on a mismatched report DB (exit 3).
 *
 * Lets callers show the exact DB state without spawning a separate
 * `check-db-version`. Returns null when the output carries no such line
 * (older lib, or a different failure), in which case callers fall back to
 * running the check themselves.
 *
 * @param stdout Full captured stdout of the failed fi-steps / fi-run process.
 * @returns The parsed check result, or null if none is present.
 */
export function parseReportDbCheckFromOutput(stdout: string): IReportDbCheck | null {
    const parsed = parseLastJsonLine(stdout);
    if (!parsed || typeof parsed.is_db_version_low !== 'boolean') {
        return null;
    }
    return toCheck(parsed);
}

/**
 * Derives the typed check result from the CLI's three-key JSON.
 *
 * The CLI only reports the flag and the two versions; the status and the
 * user-facing message are computed here so the UI has one place to read
 * them. Version numbers are compared as the CLI emits them (floats), which
 * is what the lib does too; minor versions are not expected to reach 10.
 *
 * @param parsed The JSON object printed by the CLI.
 * @returns The typed check result.
 */
function toCheck(parsed: Record<string, unknown>): IReportDbCheck {
    const low = parsed.is_db_version_low === true;
    const client = Number(parsed.client_db_version ?? 0);
    const lib = Number(parsed.flowsheet_inspector_lib_db_version ?? 0);
    const clientStr = versionStr(parsed.client_db_version) ?? '0.0';
    const libStr = versionStr(parsed.flowsheet_inspector_lib_db_version) ?? 'unknown';
    const dbFile = getIdaesDbPath();

    let status: ReportDbStatus;
    let message: string;
    if (low) {
        status = 'needs_migration';
        message = `Report database '${dbFile}' is version ${clientStr}; this version of flowsheet-inspector-lib requires ${libStr}. Upgrade the database before running.`;
    } else if (client > lib) {
        status = 'incompatible_newer';
        message = `Report database '${dbFile}' is version ${clientStr}, newer than the installed flowsheet-inspector-lib supports (${libStr}). Upgrade the library in this Python environment.`;
    } else if (client === 0) {
        status = 'missing';
        message = `Report database '${dbFile}' does not exist yet; it will be created on first run.`;
    } else {
        status = 'ok';
        message = `Report database schema ${clientStr} is compatible with ${libStr}.`;
    }
    return {
        status,
        is_db_version_low: low,
        db_file: dbFile,
        client_db_version: clientStr,
        lib_db_version: libStr,
        message,
    };
}

/**
 * Builds the result used when the CLI produced no JSON.
 *
 * `invalid` is for the CLI's own refusal (exit 1 with `ERROR:` on stderr:
 * the file exists but cannot be read as a report database), which deserves
 * a banner; `unavailable` covers everything else (old lib without the
 * module, interpreter failure) and must not block the UI.
 *
 * @param status  `invalid` or `unavailable`.
 * @param message Failure text for the banner / logs.
 * @returns A check result with no version information.
 */
function failedCheck(status: 'invalid' | 'unavailable', message: string): IReportDbCheck {
    return {
        status,
        is_db_version_low: false,
        db_file: getIdaesDbPath(),
        client_db_version: null,
        lib_db_version: null,
        message,
    };
}

/**
 * Classifies a CLI run that printed no JSON.
 *
 * @param result Captured output and exit code.
 * @returns `invalid` when the CLI reported an unreadable database itself,
 *          otherwise `unavailable`.
 */
function classifyFailure(result: { stdout: string; stderr: string; code: number | null }): IReportDbCheck {
    const stderr = result.stderr.trim();
    const errLine = stderr.split('\n').find((l) => l.startsWith('ERROR:'));
    if (result.code === 1 && errLine) {
        return failedCheck('invalid', errLine.replace(/^ERROR:\s*/, ''));
    }
    const detail = stderr || result.stdout.trim() || '(no output)';
    return failedCheck('unavailable', `Report database check failed (exit ${result.code}): ${detail.slice(0, 500)}`);
}

/**
 * Runs `check-db-version` and reports the compatibility of the report DB with
 * the installed flowsheet-inspector-lib.
 *
 * Never throws: any failure to run or parse the check collapses into status
 * `unavailable` with the failure text in `message`, so callers can simply
 * forward the result to the UI. Only `is_db_version_low` (Update button),
 * `incompatible_newer` and `invalid` need a banner.
 *
 * @param env    The resolved Python environment to check with.
 * @param dbPath Optional explicit database file (`--db`); omitted in normal
 *               use so the lib resolves the same default the extension reads.
 * @returns The check result; `status` is `unavailable` when the check itself
 *          could not be performed.
 */
export async function checkReportDb(env: IResolvedPythonEnv, dbPath?: string): Promise<IReportDbCheck> {
    let result: { stdout: string; stderr: string; code: number | null };
    try {
        result = await runDbModule(env, CHECK_DB_VERSION_MODULE, dbPath ? ['--db', dbPath] : []);
    } catch (e) {
        return failedCheck('unavailable', `Could not run report database check: ${e instanceof Error ? e.message : e}`);
    }

    const parsed = parseLastJsonLine(result.stdout);
    if (result.code !== 0 || !parsed) {
        const failure = classifyFailure(result);
        console.warn(`[report_db] check ${failure.status}: ${failure.message}`);
        return failure;
    }
    return toCheck(parsed);
}

/**
 * Runs `db-migration`, which (only when the DB is older than the lib) rebuilds
 * the report DB with the current schema, copies every row across (ids
 * preserved), keeps a backup of the old file and atomically swaps the new
 * file into place.
 *
 * Callers should pause SQLite polling around this call
 * (see pauseHistoryPolling): on Windows the final rename fails if another
 * process holds the file open.
 *
 * Never throws: a refusal (DB newer than the lib, invalid file) or failure is
 * returned with `ok: false` and the lib's message.
 *
 * @param env    The resolved Python environment whose lib performs the migration.
 * @param dbPath Optional explicit database file (`--db`); omitted in normal use.
 * @returns The migration outcome as reported by the lib.
 */
export async function migrateReportDb(env: IResolvedPythonEnv, dbPath?: string): Promise<IReportDbMigration> {
    const failed = (check: IReportDbCheck): IReportDbMigration => ({
        ...check,
        ok: false,
        migrated: false,
        backup_file: null,
        rows_migrated: 0,
    });

    let result: { stdout: string; stderr: string; code: number | null };
    try {
        result = await runDbModule(env, DB_MIGRATION_MODULE, dbPath ? ['--db', dbPath] : []);
    } catch (e) {
        return failed(failedCheck('unavailable', `Could not run report database migration: ${e instanceof Error ? e.message : e}`));
    }

    const parsed = parseLastJsonLine(result.stdout);
    if (!parsed) {
        return failed(classifyFailure(result));
    }

    // The JSON describes the DB as it was BEFORE migrating; the outcome
    // fields say what happened. Word the message accordingly.
    const before = toCheck(parsed);
    const migrated = parsed.migrated === true;
    const rows = Number(parsed.rows_migrated ?? 0);
    const ok = result.code === 0;
    let message: string;
    if (migrated) {
        message = `Migrated report database from schema ${before.client_db_version} to ${before.lib_db_version} (${rows} rows).`;
    } else if (!ok) {
        const errLine = result.stderr.trim().split('\n').find((l) => l.includes('ERROR')) ?? result.stderr.trim();
        message = `Report database migration failed: ${errLine.slice(0, 500) || `exit ${result.code}`}`;
    } else if (before.status === 'incompatible_newer') {
        message = `Cannot migrate: ${before.message}`;
    } else {
        message = `No migration needed: ${before.message}`;
    }
    return {
        ...before,
        message,
        ok,
        migrated,
        backup_file: strOrNull(parsed.backup_file),
        rows_migrated: rows,
    };
}
