// Listen to messages from the extension
const vscode = acquireVsCodeApi();

// Wait for Mermaid to be available
let mermaidReady = false;
window.addEventListener("load", () => {
    // Import mermaid dynamically
    import("https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs").then((module) => {
        window.mermaid = module.default;
        window.mermaid.initialize({ startOnLoad: false });
        mermaidReady = true;
        // Render initial diagram
        renderMermaid();
    });
});

function renderMermaid() {
    if (!mermaidReady || !window.mermaid) {
        console.log("Mermaid not ready yet");
        return;
    }

    const diagramContainer = document.getElementById("mermaidview");
    if (diagramContainer) {
        // Force Mermaid to re-render
        window.mermaid.run({
            nodes: [diagramContainer],
        });
    }
}

window.addEventListener("message", (event) => {
    const message = event.data;

    if (message.type === "update") {
        // Update file content
        const contentElement = document.getElementById("content");
        const fileNameElement = document.getElementById("file-name");
        const diagramContainer = document.getElementById("mermaidview");

        if (contentElement) {
            contentElement.textContent = message.content;
        }

        if (fileNameElement && message.fileName) {
            fileNameElement.textContent = "📄 " + message.fileName.split("/").pop();
        }

        if (diagramContainer && message.diagramContent) {
            // Update content
            diagramContainer.textContent = message.diagramContent;
            diagramContainer.removeAttribute("data-processed");

            // Re-render Mermaid diagram
            renderMermaid();
        }
    }
});

// generate flowsheet detail
const generateFlowsheetDetailBtn = document.getElementById("generate_flowsheet_detail_btn");
if (generateFlowsheetDetailBtn) {
    generateFlowsheetDetailBtn.addEventListener("click", () => {
        const dofElement = document.getElementById("dofDetail");
        dofElement.innerHTML = "Loading dof...";
        vscode.postMessage({ instruction: "generate_flowsheet_detail" });
    });
}

// event listener for flowsheet detail
// vscode will interact with this js file by post message, with message type and message data, and this file will continue listen to post message, when a new message posted it will working base on message type
window.addEventListener("message", (event) => {
    const message = event.data;
    if (message.type === "flowsheet_detail") {
        flowsheetDetailDofHandler(message);
    }

    if (message.type === "error") {
        errorPrinter(message);
    }
});

/**
 * handle flowsheet detail which a JSON file generated by structure_flowsheet (idaes-run), read dof from output data and show it in webview
 * @param {*} message
 */
function flowsheetDetailDofHandler(message) {
    try {
        const flowsheetDetailElement = document.getElementById("flowsheet_detail");
        const messageData = message.data;
        const dofElement = document.getElementById("dofDetail");

        const dofData = messageData.actions.degrees_of_freedom.steps;

        let dofHtml = Object.keys(dofData.build).map((key) => {
            return `<tr><td>${key}</td><td class="td-dof-value">${dofData.build[key]}</td></tr>`;
        });
        const tableHeaderBuild = `<tr>
                                <th>Flowsheet Unit (build)</th>
                                <th>DOF</th>
                            </tr>`;
        const tableHeaderSolveInitial = `<tr>
                                <th>Flowsheet Unit (solve initial)</th>
                                <th>DOF</th>
                            </tr>`;
        dofHtml.unshift(tableHeaderBuild);
        dofHtml = dofHtml.join("");
        console.log(dofHtml);
        dofElement.innerHTML = dofHtml;
    } catch (error) {
        errorPrinter(error);
    }
}

function errorPrinter(message) {
    const errorElement = document.getElementById("error");
    errorElement.textContent = "Error: " + message.message;
    errorElement.style.color = "red";
}
